# Generated by Django 5.1.2 on 2024-10-21 23:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Turno',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('numero_Turno', models.IntegerField(default=0)),
                ('hora_creacion_turno', models.DateTimeField(auto_now_add=True)),
                ('estado', models.CharField(choices=[('Pendiente', 'Pendiente'), ('Activo', 'Activo'), ('Finalizado', 'Finalizados')], default='Pendiente', max_length=10)),
            ],
        ),
    ]
