# Generated by Django 5.1.2 on 2024-10-22 01:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Turno', '0002_initial'),
        ('Usuario', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='turno',
            name='staff_usuario',
            field=models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.CASCADE, to='Usuario.usuario'),
        ),
    ]
