# Generated by Django 5.1.2 on 2024-10-28 23:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Turno', '0003_alter_turno_staff_usuario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='turno',
            name='estado',
            field=models.CharField(choices=[('Pendiente', 'Pendiente'), ('Activo', 'Activo'), ('Finalizado', 'Finalizado')], default='Pendiente', max_length=10),
        ),
    ]
