# Generated by Django 5.1.2 on 2024-10-28 23:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Turno', '0004_alter_turno_estado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='turno',
            name='numero_Turno',
            field=models.IntegerField(),
        ),
    ]
